from django.conf.urls import url
from django.contrib import admin

from expert.api.views import (
    ChamberCreateAPIView,
    ChamberDeleteAPIView,
    ChamberDetailAPIView,
    ChamberListAPIView,
    ChamberUpdateAPIView,
    ChamberPropertiesCreateAPIView,
    ChamberPropertiesDeleteAPIView,
    ChamberPropertiesDetailAPIView,
    ChamberPropertiesListAPIView,
    ChamberPropertiesUpdateAPIView,
    CustomerCreateAPIView,
    CustomerDeleteAPIView,
    CustomerDetailAPIView,
    CustomerListAPIView,
    CustomerUpdateAPIView,
    DataCreateAPIView,
    DataDeleteAPIView,
    DataDetailAPIView,
    DataListAPIView,
    DataUpdateAPIView,
    MarkerCreateAPIView,
    MarkerDeleteAPIView,
    MarkerDetailAPIView,
    MarkerListAPIView,
    MarkerUpdateAPIView,
    ParameterCreateAPIView,
    ParameterDeleteAPIView,
    ParameterDetailAPIView,
    ParameterListAPIView,
    ParameterUpdateAPIView,
    SensorCreateAPIView,
    SensorDeleteAPIView,
    SensorDetailAPIView,
    SensorListAPIView,
    SensorUpdateAPIView,
    SensorTypeCreateAPIView,
    SensorTypeDeleteAPIView,
    SensorTypeDetailAPIView,
    SensorTypeListAPIView,
    SensorTypeUpdateAPIView,
)

urlpatterns = [
    url(r'^chamber/$', ChamberListAPIView.as_view(), name='chamber_list'),
    url(r'^chamber/create/$', ChamberCreateAPIView.as_view(), name='chamber_list_create'),
    url(r'^chamber/(?P<pk>\d+)/$', ChamberDetailAPIView.as_view(), name='chamber_list_detail'),
    url(r'^chamber/(?P<pk>\d+)/edit/$', ChamberUpdateAPIView.as_view(), name='chamber_list_update'),
    url(r'^chamber/(?P<pk>\d+)/delete/$', ChamberDeleteAPIView.as_view(), name='chamber_list_delete'),

    url(r'^chamber-properties/$', ChamberPropertiesListAPIView.as_view(), name='chamber_properties_list'),
    url(r'^chamber-properties/create/$', ChamberPropertiesCreateAPIView.as_view(), name='chamber_properties_list_create'),
    url(r'^chamber-properties/(?P<pk>\d+)/$', ChamberPropertiesDetailAPIView.as_view(), name='chamber_properties_list_detail'),
    url(r'^chamber-properties/(?P<pk>\d+)/edit/$', ChamberPropertiesUpdateAPIView.as_view(), name='chamber_properties_list_update'),
    url(r'^chamber-properties/(?P<pk>\d+)/delete/$', ChamberPropertiesDeleteAPIView.as_view(), name='chamber_properties_list_delete'),

    url(r'^customer/$', CustomerListAPIView.as_view(), name='customer_list'),
    url(r'^customer/create/$', CustomerCreateAPIView.as_view(), name='customer_list_create'),
    url(r'^customer/(?P<pk>\d+)/$', CustomerDetailAPIView.as_view(), name='customer_list_detail'),
    url(r'^customer/(?P<pk>\d+)/edit/$', CustomerUpdateAPIView.as_view(), name='customer_list_update'),
    url(r'^customer/(?P<pk>\d+)/delete/$', CustomerDeleteAPIView.as_view(), name='customer_list_delete'),

    url(r'^data/$', DataListAPIView.as_view(), name='data_list'),
    url(r'^data/create/$', DataCreateAPIView.as_view(), name='data_list_create'),
    url(r'^data/(?P<pk>\d+)/$', DataDetailAPIView.as_view(), name='data_list_detail'),
    url(r'^data/(?P<pk>\d+)/edit/$', DataUpdateAPIView.as_view(), name='data_list_update'),
    url(r'^data/(?P<pk>\d+)/delete/$', DataDeleteAPIView.as_view(), name='data_list_delete'),

    url(r'^marker/$', MarkerListAPIView.as_view(), name='marker_list'),
    url(r'^marker/create/$', MarkerCreateAPIView.as_view(), name='marker_list_create'),
    url(r'^marker/(?P<pk>\d+)/$', MarkerDetailAPIView.as_view(), name='marker_list_detail'),
    url(r'^marker/(?P<pk>\d+)/edit/$', MarkerUpdateAPIView.as_view(), name='marker_list_update'),
    url(r'^marker/(?P<pk>\d+)/delete/$', MarkerDeleteAPIView.as_view(), name='marker_list_delete'),

    url(r'^parameter/$', ParameterListAPIView.as_view(), name='parameter_list'),
    url(r'^parameter/create/$', ParameterCreateAPIView.as_view(), name='parameter_list_create'),
    url(r'^parameter/(?P<pk>\d+)/$', ParameterDetailAPIView.as_view(), name='parameter_list_detail'),
    url(r'^parameter/(?P<pk>\d+)/edit/$', ParameterUpdateAPIView.as_view(), name='parameter_list_update'),
    url(r'^parameter/(?P<pk>\d+)/delete/$', ParameterDeleteAPIView.as_view(), name='parameter_list_delete'),

    url(r'^sensor/$', SensorListAPIView.as_view(), name='sensor_list'),
    url(r'^sensor/create/$', SensorCreateAPIView.as_view(), name='sensor_list_create'),
    url(r'^sensor/(?P<pk>\d+)/$', SensorDetailAPIView.as_view(), name='sensor_list_detail'),
    url(r'^sensor/(?P<pk>\d+)/edit/$', SensorUpdateAPIView.as_view(), name='sensor_list_update'),
    url(r'^sensor/(?P<pk>\d+)/delete/$', SensorDeleteAPIView.as_view(), name='sensor_list_delete'),

    url(r'^sensor-type/$', SensorTypeListAPIView.as_view(), name='sensor_type_list'),
    url(r'^sensor-type/create/$', SensorTypeCreateAPIView.as_view(), name='sensor_type_list_create'),
    url(r'^sensor-type/(?P<pk>\d+)/$', SensorTypeDetailAPIView.as_view(), name='sensor_type_list_detail'),
    url(r'^sensor-type/(?P<pk>\d+)/edit/$', SensorTypeUpdateAPIView.as_view(), name='sensor_type_list_update'),
    url(r'^sensor-type/(?P<pk>\d+)/delete/$', SensorTypeDeleteAPIView.as_view(), name='sensor_type_list_delete'),
]