# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        ('expert_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=50)),
                ('algorithm_src', models.CharField(max_length=50)),
                ('algorithm_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_algorithms.Algorithm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Customer')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmRunResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('runs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_import.Runs')),
                ('algorithm_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_algorithms.AlgorithmRun')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('algorithm_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_algorithms.AlgorithmRun')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmTimeResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('algorithm_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_algorithms.AlgorithmRun')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Chamber')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Parameter')),
            ],
        ),
    ]
