# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_import', '0001_initial'),
        ('expert_algorithms', '0001_initial'),
        ('expert', '0001_initial'),
    ]

    operations = [
    ]
