# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20171027_1036'),
        ('expert_algorithms', '0002_auto_20171020_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='algorithm',
            unique_together=set([('algorithm_name', 'algorithm_src')]),
        ),
        migrations.AlterUniqueTogether(
            name='algorithmrun',
            unique_together=set([('algorithm', 'customer', 'date_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='algorithmrunresults',
            unique_together=set([('algorithm_run', 'parameter', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='algorithmtimeresults',
            unique_together=set([('algorithm_run', 'parameter', 'chamber', 'start_time', 'end_time')]),
        ),
    ]
