# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expert_algorithms', '0011_auto_20180320_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmsettings',
            name='configuration_thread',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
