# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0031_recipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sensor',
        ),
        migrations.AddField(
            model_name='data',
            name='sensor_parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expert.SensorParameter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_position',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_short_name',
        ),
    ]
