# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('property_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('step_time', models.IntegerField(default=0)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Chamber')),
            ],
        ),
    ]
