# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_import', '0001_initial'),
        ('expert_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_upload.FileUploadModel'),
        ),
        migrations.AddField(
            model_name='runproperties',
            name='runs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_import.Runs'),
        ),
    ]
