# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20171027_1036'),
        ('expert_import', '0002_auto_20171020_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='runproperties',
            unique_together=set([('property_name', 'runs')]),
        ),
        migrations.AlterUniqueTogether(
            name='runs',
            unique_together=set([('start_time', 'end_time', 'chamber')]),
        ),
    ]
