# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_auto_20171124_1010'),
        ('expert_import', '0003_auto_20171027_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert.Recipe'),
            preserve_default=False,
        ),
    ]
