# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_import', '0005_auto_20171124_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert_upload.FileUploadModel'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
