# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_import', '0006_auto_20180130_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='file',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='expert_upload.FileUploadModel'),
        ),
    ]
