# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_import', '0007_auto_20180202_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert_upload.FileUploadModel'),
        ),
    ]
