# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_import', '0009_auto_20180219_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunValueConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_string', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='runvalue',
            unique_together=set([('run', 'run_parameter')]),
        ),
    ]
