# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_auto_20171124_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
