# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0033_auto_20180327_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorparameter',
            name='live_value',
            field=models.FloatField(null=True),
        ),
    ]
