# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0004_auto_20171026_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chamber',
            unique_together=set([('chamber_name', 'customer')]),
        ),
        migrations.AlterUniqueTogether(
            name='chamberproperties',
            unique_together=set([('property_name', 'property_value', 'chamber')]),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('contact_email', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('time', 'sensor', 'parameter')]),
        ),
        migrations.AlterUniqueTogether(
            name='marker',
            unique_together=set([('time', 'marker_name', 'chamber')]),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([('serial_number', 'chamber')]),
        ),
        migrations.AlterUniqueTogether(
            name='sensortype',
            unique_together=set([('sensor_type',)]),
        ),
    ]
