# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('options', models.CharField(max_length=1000)),
                ('parser_config', models.FileField(blank=True, null=True, upload_to='config/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
                ('chamber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.Chamber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Customer')),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert_upload.FileType')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.Sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=('filer.file',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
