# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20171027_1036'),
        ('expert_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filetype',
            unique_together=set([('customer', 'parser_config'), ('name', 'customer')]),
        ),
    ]
