# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_upload', '0002_auto_20171027_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(default='Octiv', max_length=50),
        ),
    ]
