# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-27 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0032_auto_20180327_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorparameter',
            unique_together=set([('sensor', 'parameter')]),
        ),
    ]
