# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20171026_1300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set([('parameter_name', 'parameter_position')]),
        ),
    ]
