# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_description',
            new_name='parameter_position',
        ),
    ]
