# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_auto_20171114_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='owner',
            new_name='user',
        ),
    ]
