# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0013_auto_20171120_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
