# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-24 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0014_step_step_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set([('name', 'customer')]),
        ),
        migrations.RemoveField(
            model_name='step',
            name='end',
        ),
        migrations.RemoveField(
            model_name='step',
            name='start',
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('recipe', 'step_number')]),
        ),
    ]
