# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_auto_20180130_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_position',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
