# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-19 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0019_remove_chamber_chamber_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChamberProperties',
            new_name='ChamberProperty',
        ),
    ]
