# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0022_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
