# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0017_auto_20180201_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberproperties',
            name='user_defined',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chamberproperties',
            name='property_name',
            field=models.CharField(max_length=50),
        ),
    ]
