# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0021_auto_20180222_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
            preserve_default=False,
        ),
    ]
