# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0020_auto_20180219_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_value', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Recipe')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipeproperties',
            unique_together=set([('recipe', 'property_name')]),
        ),
    ]
